"""
The real, final demo: an LLM (via Ollama) decides the saga steps from a
plain-English task description, and those steps run against real MCP
servers (git + SQLite). This REQUIRES Ollama running locally with a
pulled model - it will not run in an environment without one.

Run with:
    python -m scripts.run_saga_demo_llm

If you want to change the task, edit TASK_DESCRIPTION below.
"""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.agents.planning_agent import PlanningAgent, PlanValidationError
from src.config import AUDIT_DB_PATH
from src.llm.ollama_client import OllamaClient
from src.logging_utils.audit_log import AuditLog
from src.orchestration.mcp_client import MultiServerToolInvoker, ServerConfig
from src.saga.executor import SagaExecutor
from src.saga.models import ActionCategory, ActionSpec
from src.saga.registry import CompensationRegistry

TASK_DESCRIPTION = (
    "Create a git branch called 'feature/llm-demo', commit a file called "
    "notes.txt with the content 'generated by an LLM plan' and the "
    "message 'add llm demo notes', then seed the database with an EMPTY "
    "list of rows so the pipeline fails on purpose and you can watch the "
    "rollback happen."
)

TOOL_DESCRIPTIONS = {
    "create_branch": "Create a git branch. arguments: {branch_name: string}",
    "commit_file": (
        "Write a file and commit it. arguments: {path: string, content: "
        "string, message: string}"
    ),
    "seed_database": "Insert rows into the database. arguments: {rows: list of strings}",
}


def _force_remove_readonly(func, path, exc_info) -> None:
    os.chmod(path, stat.S_IWRITE)
    func(path)


def setup_test_repo(repo_dir: Path) -> None:
    repo_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run(["git", "init", "-q"], cwd=repo_dir, check=True)
    subprocess.run(["git", "config", "user.email", "demo@example.com"], cwd=repo_dir, check=True)
    subprocess.run(["git", "config", "user.name", "Saga Demo"], cwd=repo_dir, check=True)
    (repo_dir / "README.md").write_text("# saga demo repo\n")
    subprocess.run(["git", "add", "."], cwd=repo_dir, check=True)
    subprocess.run(["git", "commit", "-q", "-m", "initial commit"], cwd=repo_dir, check=True)


def print_repo_state(repo_dir: Path, label: str) -> None:
    branches = subprocess.run(
        ["git", "--no-pager", "branch"], cwd=repo_dir, capture_output=True, text=True, timeout=15
    ).stdout.strip()
    log = subprocess.run(
        ["git", "--no-pager", "log", "--oneline"], cwd=repo_dir, capture_output=True, text=True, timeout=15
    ).stdout.strip()
    print(f"\n--- repo state ({label}) ---")
    print("branches:\n" + branches)
    print("commits:\n" + log)


def build_registry() -> CompensationRegistry:
    registry = CompensationRegistry()
    registry.register(
        ActionSpec(
            tool_name="create_branch",
            category=ActionCategory.COMPENSABLE,
            compensating_tool="delete_branch",
            compensation_arg_mapper=lambda args: {"branch_name": args["branch_name"]},
        )
    )
    registry.register(ActionSpec(tool_name="delete_branch", category=ActionCategory.COMPENSABLE, compensating_tool="_noop_delete"))
    registry.register(
        ActionSpec(
            tool_name="commit_file",
            category=ActionCategory.COMPENSABLE,
            compensating_tool="revert_last_commit",
            compensation_arg_mapper=lambda args: {},
        )
    )
    registry.register(ActionSpec(tool_name="revert_last_commit", category=ActionCategory.COMPENSABLE, compensating_tool="_noop_revert"))
    registry.register(
        ActionSpec(
            tool_name="seed_database",
            category=ActionCategory.COMPENSABLE,
            compensating_tool="wipe_database",
            compensation_arg_mapper=lambda args: {},
        )
    )
    registry.register(ActionSpec(tool_name="wipe_database", category=ActionCategory.COMPENSABLE, compensating_tool="_noop_wipe"))
    for name in ("_noop_delete", "_noop_revert", "_noop_wipe"):
        registry.register(ActionSpec(tool_name=name, category=ActionCategory.PIVOT))
    return registry


def main() -> None:
    work_dir = Path(tempfile.mkdtemp(prefix="saga_demo_llm_"))
    repo_dir = work_dir / "repo"
    db_path = work_dir / "saga_demo.sqlite3"

    setup_test_repo(repo_dir)
    print_repo_state(repo_dir, "before saga")

    invoker = MultiServerToolInvoker()
    invoker.register_tools(
        ServerConfig(command=sys.executable, args=["-m", "src.mcp_servers.git_server", str(repo_dir)]),
        tool_names=["create_branch", "delete_branch", "commit_file", "revert_last_commit"],
    )
    invoker.register_tools(
        ServerConfig(command=sys.executable, args=["-m", "src.mcp_servers.db_server", str(db_path)]),
        tool_names=["seed_database", "wipe_database", "count_rows"],
    )

    registry = build_registry()

    print("\n[llm] asking the local model to plan the steps...")
    llm_client = OllamaClient()
    planner = PlanningAgent(
        agent_id="planner_1",
        registry=registry,
        llm_call=llm_client.generate,
        tool_descriptions=TOOL_DESCRIPTIONS,
    )

    try:
        plan = planner.plan(TASK_DESCRIPTION)
    except PlanValidationError as exc:
        print(f"[llm] the model produced an invalid plan, refusing to execute: {exc}")
        shutil.rmtree(work_dir, onerror=_force_remove_readonly)
        return

    print("[llm] plan received:")
    for tool_name, arguments in plan:
        print(f"  - {tool_name}({arguments})")

    audit_log = AuditLog(db_path=AUDIT_DB_PATH)
    executor = SagaExecutor(registry, invoker, audit_log=audit_log)

    print("\n[saga] executing LLM-generated plan...")
    tracker = executor.run(plan, agent_id="planner_1")

    print(f"[saga] final status: {tracker.record.status.value}")
    for step in tracker.record.steps:
        print(f"  - {step.tool_name}: {step.status.value} (reason={step.failure_reason.value})")

    print_repo_state(repo_dir, "after saga rollback")

    audit_log.close()
    shutil.rmtree(work_dir, onerror=_force_remove_readonly)
    print(f"\n[cleanup] removed {work_dir}")
    print(f"[audit] full trail persisted at {AUDIT_DB_PATH}")


if __name__ == "__main__":
    main()
